


SCRIPTS = runsim

# export CP              := cp -rf
# export RM              := rm -rf
export INSTALL_PATH      :=/usr/local/bin

all: usage

usage:
	@echo "Usage: make [COMMANDS]"
	@echo ""
	@echo "COMMANDS"
	@echo "  install     install scripts to $(INSTALL_PATH)"

install:
	@cp -f runsim $(INSTALL_PATH)



